"""
Refinement runner: git snapshot, context loading, RefinementAgent execution.
Runs in a thread; does not set WORKSPACE_PATH env (thread-safe).
"""
import logging
import os
import uuid
from pathlib import Path
from typing import Callable, Optional, List, Dict, Any

logger = logging.getLogger(__name__)

# Maximum retries when the agent completes without writing files
MAX_AGENT_RETRIES = 2


def _git_snapshot(workspace_path: Path) -> str:
    """Create a pre-refinement git commit in the workspace. Returns message."""
    try:
        import git
    except ImportError:
        logger.warning("gitpython not installed; skipping pre-refinement snapshot")
        return "Git snapshot skipped (git not available)"
    if os.getenv("ENABLE_GIT", "true").lower() not in ("true", "1", "yes"):
        return "Git snapshot skipped (ENABLE_GIT=false)"
    workspace_path = Path(workspace_path)
    try:
        if not (workspace_path / ".git").exists():
            repo = git.Repo.init(workspace_path)
            gitignore = workspace_path / ".gitignore"
            if not gitignore.exists():
                gitignore.write_text("__pycache__/\n*.pyc\n.pytest_cache/\n.coverage\nhtmlcov/\n.env\n", encoding="utf-8")
            repo.index.add([".gitignore"])
        else:
            repo = git.Repo(workspace_path)
        repo.git.add(A=True)
        if repo.is_dirty(untracked_files=True) or repo.untracked_files:
            commit = repo.index.commit("pre-refinement snapshot")
            return f"Git snapshot created: {commit.hexsha[:7]}"
        return "No changes to snapshot (working tree clean)"
    except Exception as e:
        logger.warning("Pre-refinement git snapshot failed: %s", e)
        return f"Git snapshot skipped: {e}"


def _workspace_has_changes(workspace_path: Path) -> bool:
    """Check if the workspace has uncommitted changes (i.e. agent wrote files)."""
    try:
        import git
    except ImportError:
        # Can't verify without git; assume changes were made
        return True
    workspace_path = Path(workspace_path)
    try:
        if not (workspace_path / ".git").exists():
            return True  # No git repo; can't verify
        repo = git.Repo(workspace_path)
        # Check for any modified, added, or untracked files
        return repo.is_dirty(untracked_files=True) or bool(repo.untracked_files)
    except Exception as e:
        logger.warning("Could not check workspace changes: %s", e)
        return True  # Err on the side of trusting the agent


def _load_tech_stack(workspace_path: Path) -> Optional[str]:
    """Load tech_stack.md content if present."""
    p = workspace_path / "tech_stack.md"
    if p.exists():
        try:
            return p.read_text(encoding="utf-8")
        except Exception as e:
            logger.warning("Could not read tech_stack.md: %s", e)
    return None


def _load_file_listing(workspace_path: Path) -> str:
    """Recursively list workspace files (for agent context). Uses file_tools with explicit path."""
    from src.llamaindex_crew.tools.file_tools import file_lister
    return file_lister(".", workspace_path=str(workspace_path))


def _load_file_content(workspace_path: Path, file_path: str) -> Optional[str]:
    """Load content of a file relative to workspace."""
    from src.llamaindex_crew.tools.file_tools import file_reader
    try:
        return file_reader(file_path, workspace_path=str(workspace_path))
    except Exception as e:
        logger.warning("Could not read %s: %s", file_path, e)
        return None


# File extensions considered as modifiable source code
_SOURCE_EXTENSIONS = {
    '.js', '.jsx', '.ts', '.tsx', '.py', '.java', '.rb', '.go', '.rs',
    '.c', '.cpp', '.h', '.hpp', '.cs', '.swift', '.kt',
    '.html', '.htm', '.css', '.scss', '.less', '.sass',
    '.json', '.yaml', '.yml', '.toml', '.xml',
    '.md', '.txt', '.sh', '.bash',
}

# Directories to skip during recursive scanning
_SKIP_DIRS = {'.git', '__pycache__', 'node_modules', '.pytest_cache', 'htmlcov', '.tox', 'venv', '.venv'}

# Internal job artifacts generated by the platform — never hand these to the refinement agent
_INTERNAL_ARTIFACT_PATTERNS = (
    "state_", "tasks_", "tech_stack.md", "import_index_manifest.json",
    "delivery_mode_triage.json", "agent_backstories.json", "crew_errors.log",
)

# Max characters to inline per file (prevent huge files from blowing the context)
_MAX_INLINE_CHARS = 8000

# Max total characters for all inlined files combined
_MAX_TOTAL_INLINE_CHARS = 50000


def _is_internal_artifact(name: str) -> bool:
    """Return True if the filename is a platform-generated artifact that agents must not touch."""
    return any(name.startswith(p) or name == p for p in _INTERNAL_ARTIFACT_PATTERNS)


def _discover_source_files(workspace_path: Path) -> List[str]:
    """Recursively discover modifiable source files in the workspace.
    Excludes internal job artifacts and returns relative paths sorted alphabetically."""
    workspace_path = Path(workspace_path)
    results: List[str] = []
    for item in sorted(workspace_path.rglob("*")):
        if any(part in _SKIP_DIRS for part in item.parts):
            continue
        if not item.is_file():
            continue
        if _is_internal_artifact(item.name):
            continue
        if item.suffix.lower() in _SOURCE_EXTENSIONS:
            results.append(str(item.relative_to(workspace_path)))
    return results


def _preload_source_files(workspace_path: Path, file_paths: List[str]) -> Dict[str, str]:
    """Pre-read source files, respecting per-file and total size limits.
    Returns dict mapping relative path -> content (truncated if needed)."""
    contents: Dict[str, str] = {}
    total = 0
    for fp in file_paths:
        if total >= _MAX_TOTAL_INLINE_CHARS:
            break
        full = workspace_path / fp
        try:
            text = full.read_text(encoding="utf-8", errors="replace")
            if len(text) > _MAX_INLINE_CHARS:
                text = text[:_MAX_INLINE_CHARS] + "\n... (truncated)"
            contents[fp] = text
            total += len(text)
        except Exception as e:
            logger.warning("Could not preload %s: %s", fp, e)
    return contents


def run_refinement(
    job_id: str,
    workspace_path: Path,
    prompt: str,
    refinement_id: str,
    job_db: Any,
    progress_callback: Callable[[str, int, Optional[str]], None],
    file_path: Optional[str] = None,
    previous_status: str = "completed",
    enhanced: bool = False,
) -> Dict[str, Any]:
    """
    Run refinement: snapshot, build context, run RefinementAgent, update DB.

    Call this from a background thread. Does not mutate os.environ.

    Args:
        job_id: Job ID (for budget and DB).
        workspace_path: Job workspace root.
        prompt: User refinement prompt.
        refinement_id: ID for the refinement record.
        job_db: JobDatabase instance.
        progress_callback: callback(phase, progress, message).
        file_path: Optional target file path (relative to workspace).
        previous_status: Job status to restore when refinement completes or fails.
        enhanced: True for import-mode jobs (`job_mode=import`); uses richer project-wide
            refinement when EnhancedRefinementAgent is available; otherwise same as project-wide.

    Returns:
        {"status": "success"} or {"status": "error", "error": "..."}.
    """
    workspace_path = Path(workspace_path)
    progress_callback("refining", 5, "Creating git snapshot...")
    _git_snapshot(workspace_path)

    if enhanced:
        logger.info("Import job refinement (enhanced=True): using project-wide refinement path")

    progress_callback("refining", 10, "Loading context...")
    tech_stack_content = _load_tech_stack(workspace_path)
    file_listing = _load_file_listing(workspace_path)
    refinement_history = job_db.get_refinement_history(job_id, limit=10)
    # Exclude current (running) refinement from history context
    refinement_history = [r for r in refinement_history if r.get("id") != refinement_id]

    if file_path:
        # ── FILE-LEVEL SCOPE ──────────────────────────────────────────
        return _run_single_file_refinement(
            job_id=job_id,
            workspace_path=workspace_path,
            prompt=prompt,
            refinement_id=refinement_id,
            job_db=job_db,
            progress_callback=progress_callback,
            file_path=file_path,
            tech_stack_content=tech_stack_content,
            file_listing=file_listing,
            refinement_history=refinement_history,
            previous_status=previous_status,
        )
    else:
        # ── PROJECT-WIDE SCOPE ────────────────────────────────────────
        return _run_project_wide_refinement(
            job_id=job_id,
            workspace_path=workspace_path,
            prompt=prompt,
            refinement_id=refinement_id,
            job_db=job_db,
            progress_callback=progress_callback,
            tech_stack_content=tech_stack_content,
            file_listing=file_listing,
            refinement_history=refinement_history,
            previous_status=previous_status,
        )


def _run_single_file_refinement(
    job_id: str,
    workspace_path: Path,
    prompt: str,
    refinement_id: str,
    job_db: Any,
    progress_callback: Callable[[str, int, Optional[str]], None],
    file_path: str,
    tech_stack_content: Optional[str],
    file_listing: Optional[str],
    refinement_history: List[Dict[str, Any]],
    previous_status: str = "completed",
) -> Dict[str, Any]:
    """Run refinement targeting a single file. Retries once if no files written."""
    initial_file_content = _load_file_content(workspace_path, file_path)

    progress_callback("refining", 20, f"Refining {file_path}...")
    agent_response = None
    files_changed = False

    for attempt in range(1, MAX_AGENT_RETRIES + 1):
        try:
            from src.llamaindex_crew.agents.refinement_agent import RefinementAgent
            agent = RefinementAgent(workspace_path=workspace_path, project_id=job_id)

            if attempt > 1:
                progress_callback("refining", 25,
                    f"Retry {attempt}/{MAX_AGENT_RETRIES}: agent didn't write files, re-running...")
                logger.warning("File refinement attempt %d/%d for %s", attempt, MAX_AGENT_RETRIES, file_path)

            agent_response = agent.run(
                user_prompt=prompt,
                file_path=file_path,
                tech_stack_content=tech_stack_content,
                file_listing=file_listing,
                refinement_history=refinement_history,
                initial_file_content=initial_file_content,
            )
            logger.info("File refinement response (attempt %d, %s): %s",
                        attempt, file_path, str(agent_response)[:500])
        except Exception as e:
            logger.exception("File refinement failed for %s: %s", file_path, e)
            return _fail_refinement(job_db, job_id, refinement_id, progress_callback, str(e), previous_status)

        # Verify: either git shows changes (write/modify) or the target file was deleted
        progress_callback("refining", 80, "Verifying changes...")
        file_existed_before = initial_file_content is not None
        file_deleted_now = file_existed_before and not (workspace_path / file_path).exists()
        files_changed = _workspace_has_changes(workspace_path) or file_deleted_now
        if files_changed:
            if file_deleted_now:
                logger.info("File refinement deleted %s (attempt %d)", file_path, attempt)
            else:
                logger.info("File refinement wrote changes for %s (attempt %d)", file_path, attempt)
            break
        else:
            logger.warning("File refinement wrote no files for %s (attempt %d/%d)",
                           file_path, attempt, MAX_AGENT_RETRIES)

    if not files_changed:
        error_msg = (
            f"The AI agent completed but did not modify {file_path}. "
            "Try rephrasing your request or being more specific."
        )
        return _fail_refinement(job_db, job_id, refinement_id, progress_callback, error_msg, previous_status)

    summary = f"Refinement completed — {file_path} deleted." if (file_existed_before and not (workspace_path / file_path).exists()) else f"Refinement completed — {file_path} updated."
    return _complete_refinement(workspace_path, job_db, job_id, refinement_id, progress_callback, summary, previous_status)


def _candidate_files_from_prompt(prompt: str, source_files: List[str], workspace_path: Path) -> List[str]:
    """Narrow source_files to only those that likely need changes for this prompt.

    Strategy:
    1. Strip URLs from the prompt so domain/path words don't become false-positive tokens.
    2. Extract identifier-like tokens (especially patterns with underscores like ff_*).
    3. Return only files whose content contains those tokens.
    4. Fall back to full list when no specific tokens are found or nothing matches.
    """
    import re as _re

    # Strip URLs first — we don't want "frappe", "github", "mcp" from a URL polluting tokens
    prompt_no_urls = _re.sub(r'https?://\S+', '', prompt)

    # 1. Glob/wildcard patterns like ff_*, SomePrefix_* — most specific signal
    raw_tokens = _re.findall(r'([\w]+(?:_[\w]*)*)\*', prompt_no_urls)
    # 2. Backtick or quote wrapped identifiers: `ff_graph`, "MyFunc"
    raw_tokens += _re.findall(r'[`"\']([^`"\']{2,40})[`"\']', prompt_no_urls)
    # 3. snake_case identifiers (at least one underscore between words)
    raw_tokens += _re.findall(r'\b([a-z][a-z0-9]*(?:_[a-z0-9]+)+)\b', prompt_no_urls)
    if not raw_tokens:
        # Fallback: plain words ≥5 chars that look like identifiers
        raw_tokens = _re.findall(r'\b([A-Za-z][A-Za-z0-9]{4,})\b', prompt_no_urls)

    _STOPWORDS = {
        "the", "this", "that", "and", "for", "have", "only", "with", "from",
        "into", "change", "remove", "update", "tool", "tools", "all", "other",
        "use", "code", "file", "files", "project", "just", "should", "also",
    }
    tokens = list({
        t.rstrip("*") for t in raw_tokens
        if len(t) >= 3 and t.lower().rstrip("*") not in _STOPWORDS
    })

    if not tokens:
        return source_files

    logger.info("Candidate filter tokens: %s", tokens)

    candidates: List[str] = []
    for fp in source_files:
        full = workspace_path / fp
        try:
            content = full.read_text(encoding="utf-8", errors="replace")
        except Exception:
            candidates.append(fp)
            continue
        if any(tok in content for tok in tokens):
            candidates.append(fp)

    logger.info("Candidate files (%d/%d): %s", len(candidates), len(source_files), candidates)
    return candidates if candidates else source_files


def _run_project_wide_refinement(
    job_id: str,
    workspace_path: Path,
    prompt: str,
    refinement_id: str,
    job_db: Any,
    progress_callback: Callable[[str, int, Optional[str]], None],
    tech_stack_content: Optional[str],
    file_listing: Optional[str],
    refinement_history: List[Dict[str, Any]],
    previous_status: str = "completed",
) -> Dict[str, Any]:
    """Run project-wide refinement: filter to candidate files, then refine each individually."""
    progress_callback("refining", 12, "Scanning project files...")
    all_source_files = _discover_source_files(workspace_path)
    if not all_source_files:
        return _fail_refinement(job_db, job_id, refinement_id, progress_callback,
                                "No source files found in the workspace.", previous_status)

    # Narrow to files that plausibly need changes based on the prompt
    source_files = _candidate_files_from_prompt(prompt, all_source_files, workspace_path)
    total = len(source_files)
    logger.info(
        "Project-wide scope: %d/%d candidate files: %s",
        total, len(all_source_files), source_files,
    )
    progress_callback("refining", 15, f"Refining {total} candidate files...")

    # Single pre-snapshot before processing any files
    _git_snapshot(workspace_path)

    files_modified: List[str] = []
    files_failed: List[str] = []

    for idx, fp in enumerate(source_files, start=1):
        pct = 20 + int(60 * idx / total)
        progress_callback("refining", pct, f"Refining file {idx}/{total}: {fp}...")
        initial_content = _load_file_content(workspace_path, fp)

        try:
            from src.llamaindex_crew.agents.refinement_agent import RefinementAgent
            agent = RefinementAgent(workspace_path=workspace_path, project_id=job_id)
            agent_response = agent.run(
                user_prompt=prompt,
                file_path=fp,
                tech_stack_content=tech_stack_content,
                file_listing=file_listing,
                refinement_history=refinement_history,
                initial_file_content=initial_content,
            )
            logger.info("Agent response for %s: %s", fp, str(agent_response)[:200])
        except Exception as e:
            logger.warning("Agent error on %s (skipping): %s", fp, e)
            files_failed.append(fp)
            continue

        file_deleted = initial_content is not None and not (workspace_path / fp).exists()
        if _workspace_has_changes(workspace_path) or file_deleted:
            files_modified.append(fp)
            logger.info("Changes detected for %s", fp)
        else:
            logger.info("No changes written for %s", fp)

    if not files_modified:
        reason = (
            f"Processed {total} candidate files but none were changed. "
            "The AI may not have found relevant modifications. Try being more specific."
        )
        return _fail_refinement(job_db, job_id, refinement_id, progress_callback, reason, previous_status)

    summary = (
        f"Refinement completed — modified {len(files_modified)}/{total} files: "
        f"{', '.join(files_modified)}"
    )
    if files_failed:
        summary += f"; {len(files_failed)} file(s) skipped due to errors: {', '.join(files_failed)}"
    return _complete_refinement(workspace_path, job_db, job_id, refinement_id, progress_callback, summary, previous_status)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _user_friendly_llm_error(raw_error: str) -> str:
    """Turn raw LLM/proxy errors (503, 502, 429, etc.) into a short message for the refine UI."""
    s = raw_error.strip()
    if "503" in s or "Service Unavailable" in s.lower():
        return (
            "LLM service temporarily unavailable (503). "
            "Try again in a few minutes or check your LLM endpoint configuration."
        )
    if "502" in s or "Bad Gateway" in s.lower():
        return (
            "LLM gateway error (502). The AI service may be overloaded. "
            "Try again in a few minutes."
        )
    if "429" in s or "rate limit" in s.lower() or "quota" in s.lower():
        return (
            "LLM rate limit or quota exceeded (429). "
            "Wait a moment and try again, or check your API quota."
        )
    if "timeout" in s.lower() or "timed out" in s.lower():
        return "The AI request timed out. Try again or use a shorter refinement prompt."
    # Keep original if it's short enough; otherwise truncate and add hint
    if len(s) > 200:
        return s[:200] + "… Try rephrasing your request or selecting a different file."
    return s


def _fail_refinement(job_db, job_id, refinement_id, progress_callback, error_msg, previous_status: str = "completed"):
    """Mark refinement as failed and restore job status so dashboard shows correct state."""
    logger.error("Refinement failed: %s", error_msg)
    friendly_msg = _user_friendly_llm_error(error_msg)
    job_db.fail_refinement(refinement_id, friendly_msg)
    job_db.update_job(job_id, {
        "status": previous_status,
        "current_phase": "completed",
        "progress": 100,
        "error": None,
    })
    progress_callback("refinement_failed", 0, friendly_msg)
    return {"status": "error", "error": friendly_msg}


def _create_github_pr(workspace_path: Path, job_id: str, prompt: str, job_db) -> Optional[str]:
    """Push a new branch and open a GitHub PR for the refinement changes.

    Returns the PR URL on success, or None if skipped / failed.
    Requires GITHUB_TOKEN in environment and a git remote named 'origin' pointing to GitHub.
    """
    import re as _re
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token:
        logger.warning("GITHUB_TOKEN not set — skipping PR creation")
        return None

    try:
        import git as _git
        import urllib.request as _req
        import json as _json_pr

        repo = _git.Repo(workspace_path)
        if not repo.remotes:
            logger.warning("No git remote — skipping PR creation")
            return None

        origin_url = repo.remotes["origin"].url
        # Only handle github.com repos
        m = _re.search(r"github\.com[/:](.+?/.+?)(?:\.git)?$", origin_url)
        if not m:
            logger.warning("Remote is not GitHub (%s) — skipping PR creation", origin_url)
            return None
        repo_slug = m.group(1)  # e.g. "vyogotech/frappe-mcp-server"

        # Create and checkout a new branch
        branch = f"crew-ai/job-{job_id[:8]}"
        try:
            repo.git.checkout("-b", branch)
        except _git.exc.GitCommandError:
            # Branch may already exist — try switching to it
            repo.git.checkout(branch)

        # Stage and commit everything not yet committed
        git_name = os.getenv("GITHUB_USER_NAME", "Crew AI").strip() or "Crew AI"
        git_email = os.getenv("GITHUB_USER_EMAIL", "crew-ai@noreply.github.com").strip() or "crew-ai@noreply.github.com"
        actor = _git.Actor(git_name, git_email)
        repo.git.add(A=True)
        if repo.is_dirty(untracked_files=True) or repo.untracked_files:
            repo.index.commit(
                f"crew-ai: {prompt[:72]}",
                author=actor,
                committer=actor,
            )

        # Inject token into remote URL for push auth
        auth_url = _re.sub(
            r"https://",
            f"https://{token}@",
            origin_url if origin_url.startswith("https://") else f"https://github.com/{repo_slug}.git",
        )
        repo.remotes["origin"].set_url(auth_url)
        try:
            repo.remotes["origin"].push(f"HEAD:refs/heads/{branch}")
        finally:
            # Restore original URL (don't persist the token)
            repo.remotes["origin"].set_url(origin_url)

        # Detect the default branch via GitHub API
        default_branch = "main"
        try:
            repo_api_url = f"https://api.github.com/repos/{repo_slug}"
            repo_req = _req.Request(repo_api_url, headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
            })
            with _req.urlopen(repo_req, timeout=10) as repo_resp:
                repo_info = _json_pr.loads(repo_resp.read())
            default_branch = repo_info.get("default_branch", "main")
        except Exception:
            pass
        logger.info("PR base branch: %s (repo: %s)", default_branch, repo_slug)

        # Create the PR via GitHub API
        pr_body = {
            "title": f"[Crew AI] {prompt[:72]}",
            "head": branch,
            "base": default_branch,
            "body": (
                f"**Automated PR from Crew AI**\n\n"
                f"**Job:** `{job_id}`\n\n"
                f"**Request:**\n> {prompt}\n\n"
                "---\n*Generated by OPL Crew AI import & iterate workflow.*"
            ),
        }
        api_url = f"https://api.github.com/repos/{repo_slug}/pulls"
        req = _req.Request(
            api_url,
            data=_json_pr.dumps(pr_body).encode(),
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with _req.urlopen(req, timeout=15) as resp:
            pr_data = _json_pr.loads(resp.read())
        pr_url = pr_data.get("html_url", "")
        logger.info("PR created: %s", pr_url)
        return pr_url

    except Exception as e:
        logger.warning("PR creation failed (non-fatal): %s", e)
        return None


def _complete_refinement(workspace_path, job_db, job_id, refinement_id, progress_callback, message, previous_status: str = "completed"):
    """Mark refinement as completed and restore job status so dashboard shows correct state."""
    try:
        _git_snapshot(workspace_path)
    except Exception as e:
        logger.warning("Post-refinement git snapshot failed: %s", e)

    # Attempt to push a branch and open a PR if this is an import job with a GitHub remote
    pr_url: Optional[str] = None
    try:
        job = job_db.get_job(job_id)
        meta = job.get("metadata") or {} if job else {}
        if isinstance(meta, str):
            import json as _jm
            try:
                meta = _jm.loads(meta)
            except Exception:
                meta = {}
        if meta.get("job_mode") == "import":
            refinements = job_db.get_refinement_history(job_id, limit=1)
            prompt = refinements[0].get("prompt", "") if refinements else ""
            progress_callback("completed", 95, "Creating GitHub PR...")
            pr_url = _create_github_pr(Path(workspace_path), job_id, prompt, job_db)
            if pr_url:
                meta["pr_url"] = pr_url
                import json as _jmu
                job_db.update_job(job_id, {"metadata": _jmu.dumps(meta)})
    except Exception as e:
        logger.warning("Post-refinement PR step failed (non-fatal): %s", e)

    job_db.complete_refinement(refinement_id)
    job_db.update_job(job_id, {
        "status": previous_status,
        "current_phase": "completed",
        "progress": 100,
        "error": None,
    })
    done_msg = f"{message} — PR: {pr_url}" if pr_url else message
    progress_callback("completed", 100, done_msg)
    return {"status": "success", "pr_url": pr_url}
