"""
End-to-end tests for the configurable SoftwareDevWorkflow in dynamic adaptive/fast mode.
"""
import sys
import os
import shutil
from pathlib import Path
from dotenv import load_dotenv
import traceback

# Add src to path
_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_root))
sys.path.insert(0, str(_root / "agent"))
sys.path.insert(0, str(_root / "agent" / "src"))

from llamaindex_crew.main import run_workflow
from llamaindex_crew.config import ConfigLoader

import pytest
import json

@pytest.mark.parametrize("capability_profile", ["fast", "adaptive", "full"])
def test_dynamic_workflow_e2e(capability_profile):
    """Test LlamaIndex workflow across multiple capability profiles."""
    load_dotenv()
    
    workspace_name = f"test_workspace_{capability_profile}_e2e"
    workspace_path = Path(__file__).parent / workspace_name
    if workspace_path.exists():
        shutil.rmtree(workspace_path)
    workspace_path.mkdir(exist_ok=True)
    
    # We provide a very simple vision to see how the router handles it across modes.
    vision = "Create a simple Python hello world script. No UI, no tests, just a print statement."
    
    print("=" * 80)
    print(f"🧪 E2E Test: Dynamic Workflow ({capability_profile.upper()} MODE)")
    print("=" * 80)
    
    # Pre-setup a job.json so job_metadata can be loaded with the respective mode and auto-approve reviews
    with open(workspace_path / "job.json", "w") as f:
        json.dump({
            "capability_profile": capability_profile,
            "solution_approved": True,
            "pending_review_approved": True
        }, f)
    
    try:
        results = run_workflow(
            vision=vision,
            project_id=workspace_name,
            workspace_path=str(workspace_path)
        )
        
        print(f"\nStatus: {results['status']}")
        
        # Verify key artifacts exist (all workflows should eventually generate these or their equivalents)
        tech_stack_path = workspace_path / "tech_stack.md"
        user_stories_path = workspace_path / "user_stories.md"
        
        if tech_stack_path.exists():
            print("✅ tech_stack.md generated")
        else:
            print("❌ tech_stack.md (missing)")
            raise AssertionError("tech_stack.md not generated by workflow")
            
        if user_stories_path.exists():
            print("✅ user_stories.md generated")
        else:
            print("❌ user_stories.md (missing)")
            raise AssertionError("user_stories.md not generated by workflow")
            
        src_dir = workspace_path / "src"
        if src_dir.exists():
            src_files = list(src_dir.rglob("*.py"))
            print(f"\n📝 Found {len(src_files)} Python files in src/")
        
        print(f"\n✅ E2E Test PASSED for {capability_profile}!")
        return results
        
    except Exception as e:
        print(f"\n❌ Test failed: {e}")
        traceback.print_exc()
        raise

if __name__ == "__main__":
    test_dynamic_workflow_e2e("fast")
    test_dynamic_workflow_e2e("adaptive")
    test_dynamic_workflow_e2e("full")
